version: '2'

services:
  scoreboard:
    build: backend
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./sock:/var/run/gunicorn:rw
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
  scoreboard_watch:
    build: backend
    environment:
      - REDIS_HOST=redis
      - DATA_DIR=/data
      - PYTHONUNBUFFERED=1
    volumes:
      - /services/data:/data
    depends_on:
      - redis
    entrypoint: ["python", "-m", "scoreboard.watch"]
  redis:
    image: redis
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./front/dist:/dist:ro
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
  haproxy:
    image: haproxy
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./sock:/var/run/gunicorn:rw
    ports:
      - 80:80
