FROM python:3-slim
WORKDIR /service
ADD requirements.txt .
RUN pip install -r requirements.txt
ADD gunicorn.conf.py .
ADD scoreboard/ scoreboard/
ADD watch_entrypoint.sh .
RUN chmod +x watch_entrypoint.sh
ENTRYPOINT ["/service/watch_entrypoint.sh"]
